name: Run Jest Tests with Coverage

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc' # Ensure the Node.js version specified in .nvmrc is used

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Check coverage
        run: |
          npx jest --coverage --coverageReporters=text-summary --passWithNoTests
          coverage=$(npx jest --coverage --coverageReporters=json-summary --passWithNoTests | jq '.total')
          branches=$(echo $coverage | jq '.branches.pct')
          functions=$(echo $coverage | jq '.functions.pct')
          lines=$(echo $coverage | jq '.lines.pct')
          statements=$(echo $coverage | jq '.statements.pct')

          if (( $(echo "$branches < 80" |bc -l) )) || (( $(echo "$functions < 80" |bc -l) )) || (( $(echo "$lines < 80" |bc -l) )) || (( $(echo "$statements < 80" |bc -l) )); then
            echo "Coverage threshold not met"
            exit 1
          else
            echo "Coverage threshold met"
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/
